- "activity_student:index"
- "activity_student:show"


- "attachment:index"
- "attachment:show"



- "attend_scholastic_period_evaluation:index"
- "attend_scholastic_period_evaluation:show"


- "attend_scholastic_period:index"
- "attend_scholastic_period:show"


- "attend:index"
- "attend:show"


- "classroom:index"
- "classroom:show"


- "collaborator:index"
- "collaborator:show"


- "configure_activity:index"
- "configure_activity:show"


- "contact:index"
- "contact:show"
- "contact:create"


- "course:index"
- "course:show"


- "department:index"
- "department:show"


- "event:index"
- "event:show"


- "extra_activity:index"
- "extra_activity:show"


- "phase:index"
- "phase:show"


- "evaluation_type:index"
- "evaluation_type:show"


- "local:index"
- "local:show"


- "news_letter:index"
- "news_letter:show"
- "news_letter:create"



- "news:index"
- "news:show"


- "parent:index"
- "parent:show"


- "scholastic_period:index"
- "scholastic_period:show"


- "school:index"
- "school:show"


- "serve:index"
- "serve:show"


- "staff:index"
- "staff:show"


- "statistic:index"
- "statistic:show"


- "student:index"
- "student:show"


- "table_description:index"
- "table_description:show"


- "theme:index"
- "theme:show"


- "user:index"
- "user:show"

