- "activity_student:index"
- "activity_student:show"
- "activity_student:create"
- "activity_student:update"
- "activity_student:destroy"
- "activity_student:print"

- "attachment:index"
- "attachment:show"
- "attachment:create"
- "attachment:update"
- "attachment:destroy"
- "attachment:print"


- "attend_scholastic_period_evaluation:index"
- "attend_scholastic_period_evaluation:show"
- "attend_scholastic_period_evaluation:create"
- "attend_scholastic_period_evaluation:update"
- "attend_scholastic_period_evaluation:destroy"
- "attend_scholastic_period_evaluation:print"

- "attend_scholastic_period:index"
- "attend_scholastic_period:show"
- "attend_scholastic_period:create"
- "attend_scholastic_period:update"
- "attend_scholastic_period:destroy"
- "attend_scholastic_period:print"

- "attend:index"
- "attend:show"
- "attend:create"
- "attend:update"
- "attend:destroy"
- "attend:print"

- "classroom:index"
- "classroom:show"
- "classroom:create"
- "classroom:update"
- "classroom:destroy"
- "classroom:print"

- "collaborator:index"
- "collaborator:show"
- "collaborator:create"
- "collaborator:update"
- "collaborator:destroy"
- "collaborator:print"

- "configure_activity:index"
- "configure_activity:show"
- "configure_activity:create"
- "configure_activity:update"
- "configure_activity:destroy"
- "configure_activity:print"

- "contact:index"
- "contact:show"
- "contact:create"
- "contact:update"
- "contact:destroy"
- "contact:print"

- "course:index"
- "course:show"
- "course:create"
- "course:update"
- "course:destroy"
- "course:print"

- "department:index"
- "department:show"
- "department:create"
- "department:update"
- "department:destroy"
- "department:print"

- "event:index"
- "event:show"
- "event:create"
- "event:update"
- "event:destroy"
- "event:print"


- "extra_activity:index"
- "extra_activity:show"
- "extra_activity:create"
- "extra_activity:update"
- "extra_activity:destroy"
- "extra_activity:print"

- "phase:index"
- "phase:show"
- "phase:create"
- "phase:update"
- "phase:destroy"
- "phase:print"


- "evaluation_type:index"
- "evaluation_type:show"
- "evaluation_type:create"
- "evaluation_type:update"
- "evaluation_type:destroy"
- "evaluation_type:print"

- "local:index"
- "local:show"
- "local:create"
- "local:update"
- "local:destroy"
- "local:print"

- "news_letter:index"
- "news_letter:show"
- "news_letter:create"
- "news_letter:update"
- "news_letter:destroy"
- "news_letter:print"


- "news:index"
- "news:show"
- "news:create"
- "news:update"
- "news:destroy"
- "news:print"

- "parent:index"
- "parent:show"
- "parent:create"
- "parent:update"
- "parent:destroy"
- "parent:print"

- "scholastic_period:index"
- "scholastic_period:show"
- "scholastic_period:create"
- "scholastic_period:update"
- "scholastic_period:destroy"
- "scholastic_period:print"

- "school:index"
- "school:show"
- "school:create"
- "school:update"
- "school:destroy"


- "serve:index"
- "serve:show"
- "serve:create"
- "serve:update"
- "serve:destroy"
- "serve:print"

- "staff:index"
- "staff:show"
- "staff:create"
- "staff:update"
- "staff:destroy"
- "staff:print"

- "statistic:index"
- "statistic:show"
- "statistic:create"
- "statistic:update"
- "statistic:destroy"
- "statistic:print"

- "student:index"
- "student:show"
- "student:create"
- "student:update"
- "student:destroy"
- "student:print"

- "table_description:index"
- "table_description:show"
- "table_description:create"
- "table_description:update"
- "table_description:destroy"
- "table_description:print"

- "theme:index"
- "theme:show"


- "user:index"
- "user:show"
- "user:create"
- "user:update"
- "user:destroy"
- "user:print"
