fr:
  eval_type:
    denom: "Type d'évaluation"
    values:
      contin_ss:
        denom: "Évaluation continue"
        desc: "L'évaluation continue implique l'évaluation continue des performances d'un étudiant tout au long de l'année universitaire. \
               Cela peut inclure des devoirs en classe, des devoirs, des quiz et la participation en classe. Ces évaluations sont destinées \
               fournir une rétroaction régulière sur les progrès d’un élève."
      tests_examinations:
        denom: "Tests et examens de classe"
        desc: "Students are often subjected to periodic class tests, mid-term examinations, and end-of-term examinations. \
              These assessments are used to gauge students' understanding of the subjects being taught."
      end_Sequence_exam:
        denom: "Examens de fin de séquence"
        desc: "In addition to continuous assessment, there are often end-of-sequence examinations, which are held at the \
              end of specific units or sequences of the curriculum. These assessments help measure a student's grasp of \   
              the material covered in those units."
      mock_tests_exam:
        denom: "Examens blancs"
        desc: "Mock examinations, also known as practice examinations, are often conducted prior to the official national \
              exams (such as the GCE Ordinary and Advanced Levels). These mock exams help students prepare for the \
              high-stakes final exams."
      natinal_sexam:
        denom: "National Examinations"
      practical_exam:
        denom: "Practical Examinations"
        desc: "In subjects like science and technology, practical assessments are often part of the evaluation process. \
              These evaluations may involve hands-on experiments, projects, or laboratory work."
      oral_exam:
        denom: "Oral Examinations"
        desc: "Some subjects, especially languages and oral-based courses, may include oral examinations. \
              These assessments evaluate students' speaking and communication skills"
      course_projects:
        denom: "Coursework and Projects"
        desc: "In some cases, students are required to complete coursework or projects that are submitted and graded \
              as part of the evaluation process."
      overall_performance:
        denom: "Overall Class Performance"
        desc: "Teachers often consider a student's overall class performance, which may include participation in class \
              discussions, group work, and behavior."
  diary_type:
    denom: 'diary Type'
  collab_cat:
    denom: 'Catégorie de collaborateur'
    values:
      educational_partners:
        denom: "Partenaires éducatifs"
        desc: "Les entreprises éducatives, les éditeurs et les fournisseurs de contenu peuvent \
              collaborer avec les écoles pour proposer du matériel d'apprentissage, des logiciels ou des ressources pédagogiques."
      mentorship_rograms:
        denom: "Programmes de mentorat"
        desc: "Des mentors externes ou des organisations de mentorat s'associent aux écoles \
              pour fournir aux étudiants des orientations et des conseils de carrière."
  
  course_subject:
    denom: "Matières Scientifiques"
    values:
      scien_sub:
        denom: "Matières Scientifiques"
        desc: "Les Matières scientifiques regroupent toutes les disciplines axées sur l'étude des \
              phénomènes naturels, des mathématiques et de l'application de la méthode scientifique. \
              Elle est conçue pour les étudiants souhaitant explorer les lois de la nature et \
              comprendre les principes qui régissent l'univers et la technologie."
      lit_sub:
        denom: "Matières Littéraires"
        desc: "Les Matières littéraires sont idéales pour les étudiants intéressés par l'exploration de \
              diverses cultures, l'analyse de textes littéraires, et l'étude des événements historiques. \
              Elle favorise le développement de compétences critiques, de réflexion et d'expression écrite et orale."
      comp_sub:
        denom: "Matières Complémentaires"
        desc: "Les Matières Complémentaires englobent une variété de disciplines qui enrichissent le curriculum \
              standard. Ils sont essentiels pour former des individus bien arrondis et conscients des enjeux sociaux et personnels."